### ISSUE TITLE
Problème de migrations

### ISSUE THREAD

**Issue by donnerc** [khcr/django-coursesApp#5]
Il n'est plus possible de faire correctement les migrations, car des applications existent dans `settings.py` qui n'existent en fait plus dans l'arborescence du projet (`exercices`, `quiz`, ...,)

**Comment by donnerc** [comment]
Certains modèles ne sont plus non plus disponibles, ce qui empêche également de réaliser la commande `python3 manage migrate`

```bash
$ python3 manage.py migrate
CommandError: System check identified some issues:

ERRORS:
students.Student.done_skills: (fields.E300) Field defines a relation with model 'exercises.Skill', which is either not installed, or is abstract.
```

**Comment by khcr** [comment]
Corrigé.
